version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: eqanun-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: eqanun
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: eqanun-app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/eqanun
volumes:
  pgdata:
